# Site settings
title: A Personal Website
description: Jekyll Theme Minimal Resume
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Hi, I'm Adam
user_description: I'm a doctoral student in the <a href="https://business.wsu.edu/graduate-programs/phd-business/students-grads/">Carson College of Business</a> at Washington State University where I focus my research on asset pricing, fixed income, behavioral topics, and some monetary policy.  I love to do all kinds of things, but this website acts as a repository for professional use - any of my more interesting activities will be on Twitter or Medium.   
user_title: A finance PhD and machine learning enthusiast
email: adam.bozman@wsu.edu
twitter_username: adam_bozman 
github_username:  adam-bozman
kaggle_username:  adambozman
medium_username:  bozmanadam
linkedin_username:  adam-bozman-65218b73

exclude: ['package.json', 'src' , 'node_modules']
