# Site settings
title: Hi, I'm Adam
description: 'Home Page'
url: 'http://adam-bozman.github.io/'
baseurl: ''
profilepic: '/images/linkedinprofile.jpg'
bkimage: '/images/coug.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Hi, I'm Adam'
  email: adam.bozman@wsu.edu
  twitter_username: adam_bozman
  medium_username: @bozmanadam
  github_username:  adam-bozman
  linkedin_username:  adam-bozman-65218b73
  meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
